<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductStructSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $rows = [
            [
                'produk' => 'Platinum-Sendiri',
                'plafond_min' => 1000000,
                'plafond_max' => 300000000,
                'tenor_max' => 144,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 68,
                'usia_max' => 80,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 1,
            ],
            [
                'produk' => 'Platinum-Janda',
                'plafond_min' => 1000000,
                'plafond_max' => 200000000,
                'tenor_max' => 144,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 68,
                'usia_max' => 80,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 2,
            ],
            [
                'produk' => 'Platinum-Duda',
                'plafond_min' => 1000000,
                'plafond_max' => 200000000,
                'tenor_max' => 144,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 68,
                'usia_max' => 80,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 3,
            ],
            [
                'produk' => 'Regular-Sendiri',
                'plafond_min' => 1000000,
                'plafond_max' => 500000000,
                'tenor_max' => 180,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 55,
                'usia_max' => 75,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 4,
            ],
            [
                'produk' => 'Regular-Janda',
                'plafond_min' => 1000000,
                'plafond_max' => 200000000,
                'tenor_max' => 180,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 45,
                'usia_max' => 75,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 5,
            ],
            [
                'produk' => 'Regular-Duda',
                'plafond_min' => 1000000,
                'plafond_max' => 200000000,
                'tenor_max' => 180,
                'rate_percent' => 0.14,
                'provisi_percent' => 0.01,
                'usia_masuk_min' => 55,
                'usia_max' => 75,
                'admin_percent' => 0.05,
                'blokir_angsuran' => 2,
                'taspen' => 850000,
                'tata_laksana' => 1750000,
                'tata_laksana_plus_percent' => 0.01,
                'admin_angsuran_percent' => 0.10,
                'dbr_percent' => 0.90,
                'asabri' => 350000,
                'usia_masuk_max' => 80,
                'sort_order' => 6,
            ],
            [
                'produk' => 'SG-Sendiri',
                'plafond_min' => 1500000,
                'plafond_max' => 30000000,
                'tenor_max' => 36,
                'rate_percent' => 0.30,
                'provisi_percent' => 0.02,
                'usia_masuk_min' => 55,
                'usia_max' => 85,
                'admin_percent' => 0.06,
                'blokir_angsuran' => 1,
                'taspen' => 850000,
                'tata_laksana' => 0,
                'tata_laksana_plus_percent' => 0.05,
                'admin_angsuran_percent' => 0,
                'dbr_percent' => 0.95,
                'asabri' => 350000,
                'usia_masuk_max' => null,
                'sort_order' => 7,
            ],
            [
                'produk' => 'SG-Janda',
                'plafond_min' => 1500000,
                'plafond_max' => 30000000,
                'tenor_max' => 36,
                'rate_percent' => 0.30,
                'provisi_percent' => 0.02,
                'usia_masuk_min' => 40,
                'usia_max' => 85,
                'admin_percent' => 0.06,
                'blokir_angsuran' => 1,
                'taspen' => 850000,
                'tata_laksana' => 0,
                'tata_laksana_plus_percent' => 0.05,
                'admin_angsuran_percent' => 0,
                'dbr_percent' => 0.95,
                'asabri' => 350000,
                'usia_masuk_max' => null,
                'sort_order' => 8,
            ],
            [
                'produk' => 'SG-Duda',
                'plafond_min' => 1500000,
                'plafond_max' => 30000000,
                'tenor_max' => 36,
                'rate_percent' => 0.30,
                'provisi_percent' => 0.02,
                'usia_masuk_min' => 40,
                'usia_max' => 85,
                'admin_percent' => 0.06,
                'blokir_angsuran' => 1,
                'taspen' => 850000,
                'tata_laksana' => 0,
                'tata_laksana_plus_percent' => 0.05,
                'admin_angsuran_percent' => 0,
                'dbr_percent' => 0.95,
                'asabri' => 350000,
                'usia_masuk_max' => null,
                'sort_order' => 9,
            ],
            [
                'produk' => 'SG-Yatim',
                'plafond_min' => 1500000,
                'plafond_max' => 30000000,
                'tenor_max' => 36,
                'rate_percent' => 0.30,
                'provisi_percent' => 0.02,
                'usia_masuk_min' => 17,
                'usia_max' => 25,
                'admin_percent' => 0.06,
                'blokir_angsuran' => 1,
                'taspen' => 850000,
                'tata_laksana' => 0,
                'tata_laksana_plus_percent' => 0.05,
                'admin_angsuran_percent' => 0,
                'dbr_percent' => 0.95,
                'asabri' => 350000,
                'usia_masuk_max' => null,
                'sort_order' => 10,
            ],
        ];

        foreach ($rows as &$row) {
            $row['created_at'] = $now;
            $row['updated_at'] = $now;
        }
        unset($row);

        DB::table('product_struct')->upsert(
            $rows,
            ['produk'],
            [
                'plafond_min',
                'plafond_max',
                'tenor_max',
                'rate_percent',
                'provisi_percent',
                'usia_masuk_min',
                'usia_max',
                'admin_percent',
                'blokir_angsuran',
                'taspen',
                'tata_laksana',
                'tata_laksana_plus_percent',
                'admin_angsuran_percent',
                'dbr_percent',
                'asabri',
                'usia_masuk_max',
                'sort_order',
                'updated_at',
            ]
        );
    }
}
