org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
systemProp.gradle.wrapperDistributionUrl=https\://services.gradle.org/distributions/gradle-8.15-all.zip
org.gradle.java.home=D\:\\android_studio\\jbr